# Tensorとは？
---
Pytorchでは、ディープラーニングを実装する際に必要になる基本技術に
* Pythonの基本操作
* NumPyの基本操作
* Tensorの基本操作

以上の3つが挙げられる。

3つ目に当たる、Tensorの基本操作をこの単元から学んでいくぞ。

PyTorchでは、`torch.Tensor`(テンソル)という型にデータを格納しディープラーニングを行う。  
そのため、Tensor型の理解・操作をできるとディープラーニングの理解・操作が容易になるぞ！

Tensor型の特徴を先に紹介する。

1. TensorはNumPyのndarrayに似ている
2. GPUを使って演算を行うことが可能
3. 自動微分という機能がある

この単元では、特徴**1**について学んでいくぞ！  


## この単元の目標

* Tensor型のイメージを掴む
* Tensor型の宣言・確認方法を学ぶ
* Tensor型とArray型の変換方法を学ぶ

  → **Tensor型の基礎を勉強していこう**


In [ ]:
# 前準備
# pytorchライブラリのインポート
import torch
# numpyライブラリのインポート
import numpy as np 

## Tensorの基礎 宣言の仕方
---
まずはTensorのイメージを掴んでいこう。「Tensorとは？」

特徴1：**TensorはNumPyのndarrayに似ている**
* n次元行列の演算を行うことでDLを可能にしている  

実際にプログラムを実行してTensor型のデータを作成しイメージを掴もう！

【例題】NumPyとPyTorchの関数を利用して、行列内の要素が全て0のarray型とTensor型データを生成してみよう。

In [ ]:
np.zeros((2, 3))

In [ ]:
torch.zeros((2, 3))

上記を見ても分かる通り、NumPyとPyTorchは関数名や関数の処理が非常に似ているものが多い。  
データを生成する関数だと、

* zeros()：行列内の要素が全て「0」
* ones()：行列内の要素が全て「1」
* rand()：行列内の要素が0~1のランダム

等はNumPyと同様に使用することが可能だ！

NumPyには、任意の要素を持つ行列を作成する関数に`array()`があったが  
PyTorchでは、

* tensor()：行列内の要素を一つずつ任意で指定

が代替にあたると言えるだろう。関数名は変わったが使用感は変わらないぞ！


【問題】2次元の行列`[[0,1,2], [3,4,5]]`を関数`array()`と`tensor()`を使って宣言して出力しよう。

In [ ]:
print(np.array([[0,1,2], [3,4,5]]))
print(torch.tensor([[0,1,2], [3,4,5]]))

* 
```
[[0 1 2]
 [3 4 5]]
tensor([[0, 1, 2],
        [3, 4, 5]])
```

と表示できれば成功だ。

## Tensorの基礎 中身の確認と型
---

続いて、作成したTensorの確認を行ってみよう！

【例題1】下記のプログラムを実行して結果を確認してみよう。

In [ ]:
num1 = np.zeros((2, 3))
ten1 = torch.zeros((2, 3))
print(f"num1：{num1.shape} / {num1.dtype}")
print(f"ten1：{ten1.shape} / {ten1.dtype}")
print(type(ten1))

実行結果から、どちらも2行3列で実数型を扱うことが読み取れる。

* .shape：データの形を確認
* .dtype：要素の型を確認

等の変数はNumPyと同様に使用することが可能だ！

**注意**
* NumPyとPyTorchではデフォルトの数値の型が微妙に違う
    * よく見ると`float64`と`float32`で扱う桁数が異なる

|    |  整数  |  実数  |
| :-: | :-: | :-: |
|  NumPy  |  int32  |  float64  |
|  PyTorch  |  int64  |  float32  |

また、実数と整数、デフォルトとデフォルト以外で出力に差が生まれる。知っておくと便利だ！  

【例題2】下記のプログラムを実行して結果を確認してみよう。

In [ ]:
print(torch.zeros((2, 3)))
print(torch.zeros((2, 3), dtype=torch.int32))

実数の場合、数字の後ろに 「*.*」 があることがわかる。  
また、デフォルト以外の型を扱うと`dtype`も出力される。（PyTorchの整数のデフォルトは`int64`）

テンソルの数値の型を指定したい場合はオプション`dtype`を指定する
* `dtype=torch.指定したい型`    
* https://pytorch.org/docs/stable/tensors.html (詳細は公式HPを参照)


【問題】行列内の要素が全て「1」な2行3列のTensorを宣言して出力しよう。なお、要素は`int64`型とする。

* 
```
tensor([[1, 1, 1],
        [1, 1, 1]])
```

と表示できれば成功だ。

## Tensorの基礎 array との変換
---
`Tensor`と`Array`を互いに変換し合う方法を覚えよう。

【例題1】TensorからArrayへ変換した後、再度Tensorへ変換してみよう。

In [ ]:
before = torch.zeros(3)
print(f"変換前：{before}")
after = before.numpy()
print(f"変換後：{after}")
data = torch.from_numpy(after)
print(f"再変換後：{data}")

Tensorのデータが生成され、Arrayに変換された後、再度Tensorへ変換したことを確認できた。

* Tensor→Arrayの変換方法：`変換したいTensor名.numpy()`
* Array→Tensorの変換方法：`torch.from_numpy(変換したいArray名)`

**注意**
* 上記のような変換を行った場合、**メモリを共有している**ことを念頭に置くこと

例えば、すべての要素にある値を加える.add_()メソッドを利用して、例題1のbeforeに変更を加えてみる。

【例題2】下記のプログラムを実行して結果を確認してみよう。

In [ ]:
before.add_(1)
print(f"変換前：{before}")
print(f"変換後：{after}")
print(f"再変換後：{data}")

すると上記の出力結果の通り、全ての変数の値が変更される。

この挙動を忘れずにプログラムすると良い。

【問題】`ones()`を利用して2行3列のArrayデータを作成した後、Tensorデータへ変換して出力しよう。

* 
```
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
```
と表示できれば成功だ。  
NumPyで生成したデータをTensorへ変換したとき要素の型が原因でエラーが起こることがあるぞ！