# Tensorとは？
---
前単元まで`Tensor`の特徴を学んだ。  
この単元ではTensorを利用する上で利用頻度が高い、関数などを学んでいこう！


## この単元の目標

* transposeの利用方法を学ぶ
* reshapeの利用方法を学ぶ
* zero_の利用方法を学ぶ

  → **Tensor型でよく利用する関数について勉強していこう**

In [1]:
# pytorchライブラリのインポート
import torch

## Tensorを操作する関数 transposeとreshape
---
PyTorchでTensorを扱う際に利用頻度が高い、`transpose`と`reshape`の使い方を見ていこう

それぞれの関数の働きは
* `transpose`：**行列の転置**
* `reshape`：**行列の形（サイズ）の変更**

一つずつ体験していこう。

【例題1】プログラムを実行して実行結果から挙動を確かめよう。

In [2]:
x = torch.rand((4, 3))
print(x)
print(x.transpose(0, 1))

tensor([[0.7821, 0.9240, 0.5399],
        [0.4860, 0.6607, 0.2178],
        [0.5132, 0.8345, 0.5528],
        [0.2587, 0.6404, 0.9316]])
tensor([[0.7821, 0.4860, 0.5132, 0.2587],
        [0.9240, 0.6607, 0.8345, 0.6404],
        [0.5399, 0.2178, 0.5528, 0.9316]])


4行3列の行列から3行4列の行列へ転置をすることができた。

* `Tensor名.transpose(0, 1)`で転置することができる
    * `torch.t(Tensor名)`でも同様の動作となる
    
**注意**
* NumPyのtransposeとは処理が違うので混同しないように注意が必要

【例題2】プログラムを実行して実行結果から挙動を確かめよう。

In [3]:
x = torch.ones(16)
print(x)
print(x.reshape(2, 8))
print(x.reshape(4, -1))

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
tensor([[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


要素を変えずに形状だけ変えることができた。

* `Tensor名.reshape(行, 列)`で形状を指定できる
    * 行や列の引数に`-1`を指定することで他方の次元の長さに合わせて自動で形状変換が可能。
    
【問題】Tensor`[[1,1,1], [1,2,2], [2,2,3], [3,3,3]]`を宣言した後，3行に形状変換して表示しよう。

In [4]:
y = torch.tensor([[1,1,1],[1,2,2],[2,2,3],[3,3,3]])
print(y.reshape(3, -1))

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])


- ```
tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])
```
と表示されていれば成功だ。

## Tensorを操作する関数 zero_()
---
次は`zero_()`を紹介する。

関数の働きは
* `zero_()`：**行列の全ての要素を0にする**


【例題】プログラムを実行して実行結果から挙動を確かめよう。

In [5]:
a = torch.tensor([[1,2,3],[4,5,6]]) # 手動作成
print(a)
a.zero_()# 中身をゼロ埋めにする
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0, 0, 0],
        [0, 0, 0]])


上記のプログラムのように、変数の値を残さず変更することを**インプレース(破壊的メソッド)**と呼ぶ。
* PyTorchではインプレースで変更する関数には**_**が利用されているので注意して利用しよう。

【問題】Tensor`[[1,1,1], [1,2,2], [2,2,3], [3,3,3]]`を宣言した後、zero_()を利用して要素を全て0にして表示しよう。

In [7]:
t1 = torch.tensor([[1,1,1],[1,2,2],[2,2,3],[3,3,3]])
print(t1.zero_())

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


- ```
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
```
と表示されていれば成功だ．

## まとめ
ディープラーニング実装のために、Tensorを学んだ。

* Tensor型の宣言・確認方法を学ぶ
* Tensor型とArray型の変換方法を学ぶ
* TensorのGPU演算について知る
* Tensorの自動微分機能を学ぶ

等の体験を経て、Tensorのイメージを掴んだ。

また、Tensorと共に利用する機会が多い、
* transpose
* reshape
* zero_

等の関数の使い方を学んだ。

## 次単元からの内容
ディープラーニングの実装に必要な知識

プログラム基本技術
* Pythonの基本操作
* NumPyの基本操作
* Tensorの基本操作

機械学習の手順
1. アルゴリズムの選択
2. 前処理
3. モデルの学習
4. 評価・検証

ディープラーニングの仕組み
1. 順伝播：モデルに対してデータを入力して出力を計算
2. 損失関数：予測結果と理想の結果の差を比較して、モデルがどの程度間違っているか計算
3. 逆伝播：パラメータをどう変化させれば損失が小さくなるか計算
4. 最適化：パラメータを更新してモデルをより良くする

の内容を学び終えた！

次単元からは、ディープラーニングの実装をしていくぞ！