In [2]:
import numpy as np

# モジュールがどこにあるか
np.__file__

'/opt/conda/lib/python3.11/site-packages/numpy/__init__.py'

## Numpy Arrays

In [19]:
## 普通のPythonのリスト
python_list = [1, 2, 3]
python_list


[1, 2, 3]

In [20]:
## np.array()でNumpyArrayを作成できる
np_list = np.array([1, 2, 3])
np_list


array([1, 2, 3])

In [21]:
## 入れ子
python_list_in_list = [[1, 2, 3], [4, 5, 6]]
print(python_list_in_list)

[[1, 2, 3], [4, 5, 6]]


In [24]:
## 入れ子にすると、行列になる
np_list_in_list = np.array([[1, 2, 3], [4, 5, 6]])
np_list_in_list

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
## データ型
python_list_in_list[0][0] = "a"
python_list_in_list

[['a', 2, 3], [4, 5, 6]]


In [26]:
## データ型は揃えないとエラーになる
np_list_in_list[0][0] = "a"
np_list_in_list

ValueError: invalid literal for int() with base 10: 'a'

### Numpy Arrayの演算

In [60]:
array1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array2 = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])

array1 + array2

array([[ 5,  7,  9],
       [11, 13, 15],
       [17, 19, 21]])

In [61]:
array1 - array2

array([[-3, -3, -3],
       [-3, -3, -3],
       [-3, -3, -3]])

In [62]:
array1 * array2

array([[  4,  10,  18],
       [ 28,  40,  54],
       [ 70,  88, 108]])

In [63]:
array1 / array2

array([[0.25      , 0.4       , 0.5       ],
       [0.57142857, 0.625     , 0.66666667],
       [0.7       , 0.72727273, 0.75      ]])

In [64]:
# サイズが異なるとブロードキャストされる
array3 = np.array([[1, 2, 3]])
# 上記は以下と同じ
# array3 = np.arrya([[1, 2, 3], [1, 2, 3], [1, 2, 3]])
array1 + array3

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [65]:
# ブロードキャストできない場合もある
# 以下はエラーになる
# くわしくはこちらを参照(https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)
array4 = np.array([[1, 2, 3], [4, 5, 6]])
array1 + array4


ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

## 様々な多次元配列

In [66]:
# .array([start,] stop, [step])
# 0から5まで2ずつ増やす
np.arange(0, 5, 2)


array([0, 2, 4])

In [67]:
# np.linspace(start, stop, num=50)
# 0から5まで50個の要素に分割
np.linspace(0, 5, 50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [68]:
# .copy()
# Pythonは基本、参照渡し
# .copyを使用することで、値渡しができる
ndarray = np.arange(0, 5)
ndarray_copy = ndarray.copy()
print("original array'id is {}".format(id(ndarray)))
print("copied array'id is {}".format(id(ndarray_copy)))

ndarray_copy[0] = 100
print(ndarray_copy)
print(ndarray)




original array'id is 276773945040
copied array'id is 274977024656
[100   1   2   3   4]
[0 1 2 3 4]


In [69]:
## pythonで、参照渡しされるものと値渡しされるもの
# 参照渡し
# リスト、辞書、集合、配列、データフレームなど
# 値渡し
# 整数、浮動小数点数、文字列、タプルなど

def add_world(hello):
    hello += ' world'
    return hello
 
h_str = 'hello'
h_list = ['h', 'e', 'l', 'l', 'o']
output_str = add_world(h_str)
output_list = add_world(h_list)
 
print('output_str: {}'.format(output_str))
print('output_list: {}'.format(output_list))
 
print('h_str: {}'.format(h_str)) # これは値渡し(helloのまま)
print('h_list: {}'.format(h_list)) # これは参照渡し(hello worldになる)

"""
Numpy Arrayで、コピーをする時は、.copy()を使用しないと、値を上書きしてしまうので、注意
"""


output_str: hello world
output_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']
h_str: hello
h_list: ['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']


'\nNumpy Arrayで、コピーをする時は、.copy()を使用しないと、値を上書きしてしまうので、注意\n'

In [70]:
# np.zero(shape)
shape = (2, 3)
zero = np.zeros(shape)
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [71]:
# np.ones(shape)
shape = (2, 3)
ones = np.ones(shape)
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
# np.eye(N): 単位行列を作成
np.eye(3)

"""
単位行列とは
1 0 0
0 1 0
0 0 1
のような行列で、対角成分が1で、それ以外が0の行列
"""


'\n単位行列とは\n1 0 0\n0 1 0\n0 0 1\nのような行列で、対角成分が1で、それ以外が0の行列\n'

In [73]:
# np.random_rand(d0, d1, ..., dn): ランダムな数字で行列を作れる
random_float = np.random.rand()
random_1d  = np.random.rand(3)
random_2d = np.random.rand(2, 3)

print(random_float)
print(random_1d)
print(random_2d)

0.7916545239566264
[0.53955216 0.3772692  0.36035597]
[[0.05504014 0.35280088 0.02934669]
 [0.89688319 0.23450385 0.09029586]]


In [74]:
# np.random.randn(d0, d1, ..., dn): 正規分布のランダムな数字で行列を作れる
random_normal = np.random.randn()
random_1d  = np.random.randn(3)
random_2d = np.random.randn(2, 3)

print(random_normal)
print(random_1d)
print(random_2d)



1.8670902266834177
[ 1.26922193  1.10316067 -0.0290321 ]
[[-0.84613911  0.68000643  0.56480925]
 [ 0.71642749  1.37809683 -0.59888309]]


In [75]:
# np.random.randint(low, high, size): lowからhighまでの範囲でランダムな整数を生成
random_int = np.random.randint(0, 10)
random_1d_int = np.random.randint(0, 10, 3)
random_2d_int = np.random.randint(0, 10, (2, 3))

print(random_int)
print(random_1d_int)
print(random_2d_int)

3
[3 4 6]
[[8 0 1]
 [0 5 4]]


In [77]:
# reshape: 行列の形状を変更できる
array = np.arange(0, 10)
reshaped_array = array.reshape(2, 5)
print('reshaped: {}'.format(reshaped_array))
# 行列の形状を確認
print('shape: {}'.format(reshaped_array.shape))
print('original array: {}'.format(array))

reshaped: [[0 1 2 3 4]
 [5 6 7 8 9]]
shape: (2, 5)
original array: [0 1 2 3 4 5 6 7 8 9]


## 便利な関数

In [78]:
# ランダムな正規分布を作成
normal_dist_mat = np.random.randn(5, 5)
normal_dist_mat

array([[ 0.28837825,  1.67089116, -0.28186871,  0.94635028,  1.2447674 ],
       [ 0.0186546 , -0.48487155,  0.10900986, -0.0950413 ,  1.08756974],
       [-0.95706732,  0.38360349,  1.64727573, -0.73678603, -0.20896289],
       [ 0.70023816,  1.08837069, -0.84686488, -1.42008482,  0.95646113],
       [ 0.57343725, -0.73645965, -0.38778633,  0.13583679,  1.34940527]])

In [79]:
# 最大値を取得
print('max: {}'.format(normal_dist_mat.max()))

max: 1.6708911562997535


In [80]:
# 最大値のインデックスを求める
print('max index: {}'.format(normal_dist_mat.argmax()))

max index: 1


In [83]:
# 次元を1次元に変換
normal_dist_mat.flatten()[8]

np.float64(-0.09504129785250225)

In [84]:
# 最小値
print('min: {}'.format(normal_dist_mat.min()))

# 最小値のインデックス
print('min index: {}'.format(normal_dist_mat.argmin()))

min: -1.420084816572892
min index: 18


In [85]:
# 平均値を取得
print('mean: {}'.format(normal_dist_mat.mean()))
# 中央値を取得
print('median: {}'.format(np.median(normal_dist_mat)))
# 標準偏差を取得
print('std: {}'.format(normal_dist_mat.std()))
# 分散を取得
print('var: {}'.format(normal_dist_mat.var()))

mean: 0.24177825208287124
median: 0.1358367867209207
std: 0.846755806909933
var: 0.7169953965356918


In [91]:
# 引数でaxisを指定することで、次元ごとに計算できる
# axis=0: 列ごとに計算
# axis=1: 行ごとに計算
print('original matrix: {}'.format(normal_dist_mat))
print('axis=0 列(縦): {}'.format(normal_dist_mat.max(axis=0)))
print('axis=1 行(横): {}'.format(normal_dist_mat.max(axis=1)))

original matrix: [[ 0.28837825  1.67089116 -0.28186871  0.94635028  1.2447674 ]
 [ 0.0186546  -0.48487155  0.10900986 -0.0950413   1.08756974]
 [-0.95706732  0.38360349  1.64727573 -0.73678603 -0.20896289]
 [ 0.70023816  1.08837069 -0.84686488 -1.42008482  0.95646113]
 [ 0.57343725 -0.73645965 -0.38778633  0.13583679  1.34940527]]
axis=0 列(縦): [0.70023816 1.67089116 1.64727573 0.94635028 1.34940527]
axis=1 行(横): [1.67089116 1.08756974 1.64727573 1.08837069 1.34940527]


## Numpy　Arrayの読み込み・保存

In [93]:
ndarray = np.array([[1, 2, 3], [4, 5, 6]])
# 保存
# 第一引数：ファイル名
# 第二引数：保存する配列
np.save('saved_numpy', ndarray)

In [94]:
loaded_numpy = np.load('saved_numpy.npy')
print('loaded_numpy: {}'.format(loaded_numpy))
# 保存したファイルを確認
!ls -l saved_numpy.npy
# 保存したファイルを確認
!ls -l saved_numpy.npy


loaded_numpy: [[1 2 3]
 [4 5 6]]
-rw-r--r-- 1 jovyan users 176 Mar 23 09:33 saved_numpy.npy
-rw-r--r-- 1 jovyan users 176 Mar 23 09:33 saved_numpy.npy
